#在默认情况下erureka server也是一个eureka client ,必须要指定一个 server
#eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server
eureka:
  server:
    enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 30000       # 续期时间，即清理失效节点的间隔时间,单位毫秒（默认为60000ms）
  instance:
    hostname: msrc
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/