#配置中心服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20

#swagger配置
swagger:
  switch: true
  config:
    basePackage: com.ajayhao.mslab.gateway
    title: gateway
    description: gateway
    version: 1.0