#配置中心服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20


#数据库
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@192.168.137.1:1521:orcl
    username: combs_info
    password: combs

mybatis:
  typeAliasesPackage: com.ajayhao.mslab.**.orm.entity
  mapperLocations: classpath:sqlMap/*Mapper.xml


#swagger配置
swagger:
  switch: true
  config:
    basePackage: com.ajayhao.mslab.weixinwork
    title: 企业微信功能测试
    description: 企业微信功能测试
    version: 1.0

