###  当配置中心失效时，该配置文件生效

# 服务注册
eureka:
  client:
    #间隔多久去拉取服务注册信息，单位秒，默认为30秒 上游应用及网关需要配置
    #registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}  #服务注册地址
  instance:
    #表示eureka client发送心跳给server端的频率。单位秒，默认30s
    lease-renewal-interval-in-seconds: 5
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。 默认为90s
    lease-expiration-duration-in-seconds: 20
# 数据库
jdbc:
  oracle:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.137.1:1521:orcl
    username: ajlab
    password: ajlab

#swagger配置
swagger:
  switch: true
  config:
    basePackage: com.ajayhao.mslab.stock
    title: Spring Boot中使用Swagger2构建RESTful APIs,动态刷新
    description: Micro Service Lab,/mslab/stock
    version: 1.0

# 聚合数据下游url
juhe:
  service:
    juheKey: dc585fdc8fc24cebbad73134920f9e73
    juheServiceUrl: http://web.juhe.cn:8080/finance/stock/hs?gid={gid}&key={key}

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always