#配置中心
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AjayHao/msc-config-repo
          searchPaths: /**
          username: ajay.hao@gmail.com
          password: jzH130168
      label: master

#配置中心服务注册
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10