#配置中心服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20

#元素征信配置
elecredit:
  cfg:
    userId: Z2HO3fdC
    userKey: jeEZwWbR
    elsaicUrl: http://open.elecredit.com/elsaic/?isjson=1

#swagger配置
swagger:
  switch: true
  config:
    basePackage: com.ajayhao.mslab.crawler
    title: 元素征信服务相关接口API
    description: 元数聚test,/mslab/crawler
    version: 1.0

#Actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always