eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    health-check-url-path: /actuator/health
  client:
    registry-fetch-interval-seconds: 15
    serviceUrl:
      defaultZone: http://192.168.254.132:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS